function net = cnnMNISTInit()
    % Scaling factor for randomly generated values
    f = 1 / 100;
    
    % Layer 1: Convolution Layer, 5x5 kernel, 8 features
    net.layers = {};
    
    
    net.layers{end + 1} = struct('type', 'conv', ...
                                 'weights', {{f * randn(9, 9, 1, 20, 'single'), zeros(1, 20, 'single')}}, ...
                                 'stride', 1, ...
                                 'pad', 2);
                             
                             
    % Layer 2: ReLU function
    net.layers{end + 1} = struct('type', 'relu');
    
    % Layer 3: Max Pooling Layer, 2x2 kernel
    net.layers{end + 1} = struct('type', 'pool', ...
                                 'method', 'max', ...
                                 'pool', [2 2], ...
                                 'stride', 2, ...
                                 'pad', 0);

                             
    % Layer 4: Convolution Layer, 5x5 kernel, 50 features
    net.layers{end + 1} = struct('type', 'conv', ...
                                 'weights', {{f * randn(5, 5, 20, 50, 'single'), zeros(1, 50, 'single')}}, ...
                                 'stride', 1, ...
                                 'pad', 2);
                             
    % Layer 5: ReLU function
    net.layers{end + 1} = struct('type', 'relu');
    
                             
    % Layer 7: Convolution Layer, 4x4 kernel
    net.layers{end + 1} = struct('type', 'conv', ...
                                 'weights', {{f * randn(3, 3, 50, 500, 'single'), zeros(1, 500, 'single')}}, ...
                                 'stride', 3, ...
                                 'pad', 1);
                             
    % Layer 5: ReLU function
    net.layers{end + 1} = struct('type', 'relu');
    
     % Layer 7: Convolution Layer, 4x4 kernel
    net.layers{end + 1} = struct('type', 'conv', ...
                                 'weights', {{f * randn(4, 4, 500, 10, 'single'), zeros(1, 10, 'single')}}, ...
                                 'stride', 1, ...
                                 'pad', 0);
    
    % Layer 9: Softmax
    net.layers{end + 1} = struct('type', 'softmaxloss');
end
